// Xbox PDB: EARS_Modules_PlayerGrappleSM_BuildStateMachine
// FUNC_NAME: PlayerGrappleSM::buildStateTable
// Function address: 0x007b5720
// This function builds the player grapple state machine table.
// It retrieves the state table manager, checks if the table already exists,
// creates a new one, registers it, and then populates it with states,
// transitions, animations, and behaviors.

#include <cstdint>

// Forward declarations of engine state machine functions
// (in practice these would be THUNK or inline assembly wrappers)
static int32_t getStateMachineManager(); // thunk_FUN_004dafd0
static int32_t findStateTable(int32_t manager); // FUN_00621530
static int32_t createStateTable(); // FUN_009c8f80
static void registerStateTable(const char* name, int32_t table); // FUN_004ad9d0
static int32_t getStateHandle(const char* name, int32_t unknown); // FUN_004adae0
static void addState(const char* name, int32_t stateId); // FUN_004acc70
static void setStateOnEnter(int32_t stateHandle); // FUN_007af030
static void setStateOnExit(int32_t stateHandle); // FUN_007af170
static void setStateOnUpdate(int32_t stateHandle); // FUN_007af240
static void addStateTransitionCondition(int32_t conditionId); // FUN_004acf70
static void setStateBlendParam(int32_t param1, int32_t param2, int32_t blend); // FUN_004ad0f0
static void setStateAnimation(int32_t param1, int32_t globalAnimHandle, int32_t flag); // FUN_004ad1b0
static void addStateConditional(int32_t conditionId); // FUN_004acff0
static void setStateFlag(int32_t flagId); // FUN_004ad070
static void addStateConditionalArg(int32_t arg1, int32_t arg2, int32_t arg3); // FUN_004ad170
static void addSubStateTable(const char* name, int32_t isSub); // FUN_004acf10
static void setStateOnSomething(int32_t stateHandle); // FUN_007af350
static void registerStateMachineCallback(uint32_t callbackId, void* callback, const char* name); // FUN_004adc90
static void finalizeStateTable(); // FUN_004ada40

// Global animation handles (from data section)
extern int32_t _DAT_00d5c458; // +0x??
extern int32_t DAT_00d5ef90;  // +0x??

void __thiscall PlayerGrappleSM::buildStateTable()
{
    int32_t manager;
    int32_t tableExists;
    int32_t stateTable;
    int32_t stateHandle;

    // Get the state machine manager singleton
    manager = getStateMachineManager(); // thunk_FUN_004dafd0("playerGrappleStateTable")

    // Check if the state table already exists
    tableExists = findStateTable(manager);
    if (tableExists == 0)
    {
        // Create a new state table
        stateTable = createStateTable(); // FUN_009c8f80

        // Register it globally under "playerGrappleStateTable"
        registerStateTable("playerGrappleStateTable", stateTable);

        // ---- Define states and transitions ----
        // "Valid" state entry
        stateHandle = getStateHandle("Valid", 0xffffffff); // -1 = default
        addState("GrabEndPaired", 0x13);
        addState("MultiplayerExecute", 0x56);
        addState(&DAT_00d6c3d4, 4); // some state name
        stateHandle = getStateHandle(&DAT_00d6c3d4, 0xffffffff);
        setStateOnEnter(stateHandle); // set OnEnter for that state

        stateHandle = getStateHandle("MultiplayerExecute", 0xffffffff);
        setStateOnUpdate(stateHandle); // set OnUpdate for MultiplayerExecute

        stateHandle = getStateHandle("Execution", 0xffffffff);
        setStateOnExit(stateHandle); // set OnExit for Execution

        getStateHandle("PairedFinisher", 0xffffffff); // ignore return? maybe used later

        // Set various conditions and animation parameters
        addStateTransitionCondition(0x3e);
        setStateBlendParam(0x36, 0x11, 1);
        addStateTransitionCondition(0x3a);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x3b);
        addStateTransitionCondition(0x3c);
        setStateBlendParam(0x75, 2, 1);
        setStateAnimation(0x2e, _DAT_00d5c458, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        addStateConditionalArg(0x7a, 0xffffffff, 1);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("PairedFinisherTrans", 8);
        stateHandle = getStateHandle("PairedFinisherTrans", 0xffffffff);
        addStateTransitionCondition(0x3d);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, _DAT_00d5c458, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        setStateFlag(0x3f);
        addState("GrabEndPaired", 0x13);
        addState("GrabEndPairedMasterOnlyFinisher", 0xb);
        addState("GrabKilledGrabbee", 0x30);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabStrangle", 0x3e);
        addState("RestartGrab", 0x55);
        addState("GrabEndPaired", 8);
        stateHandle = getStateHandle("GrabEndPairedMasterOnlyFinisher", 0xffffffff);
        addStateTransitionCondition(0x29);
        setStateBlendParam(0x73, 0, 1);
        addState("GrabEnd", 4);
        stateHandle = getStateHandle("GrabConcealWeaponStart", 0xffffffff);
        addState("GrabConcealWeapon", 3);
        stateHandle = getStateHandle("GrabConcealWeapon", 0xffffffff);
        addSubStateTable("playerConcealItemStateTable", 1);
        addState("GrabEnd", 0x13);
        addState(&DAT_00d6c3d4, 1);
        stateHandle = getStateHandle("GrabFront", 0xffffffff);
        setStateBlendParam(0x36, 0, 1);
        setStateBlendParam(0x16, 0, 1);
        addStateTransitionCondition(0x44);
        addStateTransitionCondition(0x4b);
        addStateTransitionCondition(0x32);
        addStateTransitionCondition(0x65);
        addStateTransitionCondition(0x68);
        setStateFlag(0x66);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addState("GrabEndPaired", 0x13);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabFrontConnected", 0x1c);
        stateHandle = getStateHandle("GrabFrontConnected", 0xffffffff);
        addStateTransitionCondition(0x65);
        setStateFlag(0x66);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabBreak", 0x45);
        addState("GrabRelease", 0x1e);
        addState("GrabDropToKnees", 0x2f);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabSlam", 0x43);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("GrabHoldThrow", 0x42);
        addState("GrabIdle", 7);
        stateHandle = getStateHandle("GrabBreak", 0xffffffff);
        addState("GrabEndPaired", 0x13);
        addState("GrabBreakPushOffCrew", 0x4c);
        addState("GrabBreakPushOffSlap", 0x4a);
        addState("GrabBreakPushOffPunch", 0x49);
        addState("GrabBreakPushOff", 4);
        stateHandle = getStateHandle("GrabBreakPushOffPunch", 0xffffffff);
        setStateBlendParam(0x16, 2, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x65);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        addStateConditional(0x2b);
        setStateFlag(0x66);
        setStateFlag(0x45);
        setStateFlag(0x42);
        addState("GrabEndPaired", 0x13);
        addState("GrabEndPaired", 8);
        stateHandle = getStateHandle("GrabBreakPushOffSlap", 0xffffffff);
        setStateBlendParam(0x16, 3, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x65);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        addStateConditional(0x2b);
        setStateFlag(0x66);
        setStateFlag(0x45);
        setStateFlag(0x42);
        addState("GrabEndPaired", 0x13);
        addState("GrabEndPaired", 8);
        stateHandle = getStateHandle("GrabBreakPushOff", 0xffffffff);
        setStateBlendParam(0x16, 1, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x65);
        addStateTransitionCondition(0x29);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x66);
        setStateFlag(0x45);
        setStateFlag(0x42);
        addState("GrabEndPaired", 0x13);
        addState("GrabEndPaired", 8);
        stateHandle = getStateHandle("GrabBreakPushOffCrew", 0xffffffff);
        setStateBlendParam(0x16, 4, 1);
        addStateTransitionCondition(0x70);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x65);
        addStateTransitionCondition(0x29);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x66);
        setStateFlag(0x45);
        setStateFlag(0x42);
        setStateFlag(0x71);
        addState("GrabEndPaired", 0x13);
        addState("GrabEndPaired", 8);
        stateHandle = getStateHandle("GrabIdle", 0xffffffff);
        setStateOnSomething(stateHandle); // set OnIdle handler
        stateHandle = getStateHandle("GrabRelease", 0xffffffff);
        setStateBlendParam(0x16, 6, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x65);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x66);
        setStateFlag(0x45);
        addStateTransitionCondition(0x29);
        addState("GrabEndPaired", 0x13);
        addState("RestartGrab", 0x57);
        addState("GrabEndPaired", 8);
        stateHandle = getStateHandle("RestartGrab", 0xffffffff);
        addStateTransitionCondition(0x2a);
        addState("GrabEndPaired", 0x13);
        addState("Valid", 4);
        stateHandle = getStateHandle("GrabQuickAttackA", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 7, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 7, 1);
        setStateBlendParam(0x75, 2, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackB", 0x1f);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabQuickAttackATrans", 8);
        stateHandle = getStateHandle("GrabQuickAttackATrans", 0xffffffff);
        setStateBlendParam(0x16, 8, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackB", 0x1f);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabQuickAttackB", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 9, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 9, 1);
        setStateBlendParam(0x75, 3, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        addStateTransitionCondition(0x76);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackC", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackCAlt", 0x23);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabQuickAttackBTrans", 8);
        stateHandle = getStateHandle("GrabQuickAttackBTrans", 0xffffffff);
        setStateBlendParam(0x16, 10, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackC", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackCAlt", 0x23);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabQuickAttackBAlt", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0xd, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0xd, 1);
        setStateBlendParam(0x75, 5, 1);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackCAlt", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackCAlt", 0x23);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabQuickAttackBAltTrans", 8);
        stateHandle = getStateHandle("GrabQuickAttackBAltTrans", 0xffffffff);
        setStateBlendParam(0x16, 0xe, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackCAlt", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackCAlt", 0x23);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabQuickAttackC", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0xb, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0xb, 1);
        setStateBlendParam(0x75, 4, 1);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        addStateTransitionCondition(0x76);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackBAlt", 0x1f);
        addState("GrabQuickAttackBAlt", 0x21);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabQuickAttackCTrans", 8);
        stateHandle = getStateHandle("GrabQuickAttackCTrans", 0xffffffff);
        setStateBlendParam(0x16, 0xc, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackBAlt", 0x1f);
        addState("GrabQuickAttackBAlt", 0x21);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabQuickAttackCAlt", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0xf, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0xf, 1);
        setStateBlendParam(0x75, 6, 1);
        addStateTransitionCondition(0x76);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackBAlt", 0x21);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabQuickAttackCAltTrans", 8);
        stateHandle = getStateHandle("GrabQuickAttackCAltTrans", 0xffffffff);
        setStateBlendParam(0x16, 0x10, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackBAlt", 0x21);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabMeleeAttackLeftA", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0x11, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0x11, 1);
        setStateBlendParam(0x75, 2, 1);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackRightC", 0x24);
        addState("GrabMeleeAttackLeftB", 0x25);
        addState("GrabMeleeAttackRightC", 0x26);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackLeftATrans", 8);
        stateHandle = getStateHandle("GrabMeleeAttackLeftATrans", 0xffffffff);
        setStateBlendParam(0x16, 0x12, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackRightC", 0x24);
        addState("GrabMeleeAttackLeftB", 0x25);
        addState("GrabMeleeAttackRightC", 0x26);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabMeleeAttackLeftB", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0x13, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0x13, 1);
        setStateBlendParam(0x75, 2, 1);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackRightC", 0x24);
        addState("GrabMeleeAttackLeftB", 0x25);
        addState("GrabMeleeAttackRightC", 0x26);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackLeftBTrans", 8);
        stateHandle = getStateHandle("GrabMeleeAttackLeftBTrans", 0xffffffff);
        setStateBlendParam(0x16, 0x14, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackRightC", 0x24);
        addState("GrabMeleeAttackLeftB", 0x25);
        addState("GrabMeleeAttackRightC", 0x26);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabMeleeAttackLeftC", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0x15, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0x15, 1);
        setStateBlendParam(0x75, 2, 1);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackRightC", 0x24);
        addState("GrabMeleeAttackLeftB", 0x25);
        addState("GrabMeleeAttackRightC", 0x26);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackLeftCTrans", 8);
        stateHandle = getStateHandle("GrabMeleeAttackLeftCTrans", 0xffffffff);
        setStateBlendParam(0x16, 0x16, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackRightC", 0x24);
        addState("GrabMeleeAttackLeftB", 0x25);
        addState("GrabMeleeAttackRightC", 0x26);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabMeleeAttackRightA", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0x17, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0x17, 1);
        setStateBlendParam(0x75, 3, 1);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackLeftC", 0x24);
        addState("GrabMeleeAttackLeftC", 0x25);
        addState("GrabMeleeAttackRightB", 0x26);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackRightATrans", 8);
        stateHandle = getStateHandle("GrabMeleeAttackRightATrans", 0xffffffff);
        setStateBlendParam(0x16, 0x18, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackLeftC", 0x24);
        addState("GrabMeleeAttackLeftC", 0x25);
        addState("GrabMeleeAttackRightB", 0x26);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabMeleeAttackRightB", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0x19, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0x19, 1);
        setStateBlendParam(0x75, 3, 1);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackLeftC", 0x24);
        addState("GrabMeleeAttackLeftC", 0x25);
        addState("GrabMeleeAttackRightB", 0x26);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackRightBTrans", 8);
        stateHandle = getStateHandle("GrabMeleeAttackRightBTrans", 0xffffffff);
        setStateBlendParam(0x16, 0x1a, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackLeftC", 0x24);
        addState("GrabMeleeAttackLeftC", 0x25);
        addState("GrabMeleeAttackRightB", 0x26);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabMeleeAttackRightC", 0xffffffff);
        addStateTransitionCondition(0x72);
        setStateBlendParam(0x16, 0x1b, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0x1b, 1);
        setStateBlendParam(0x75, 3, 1);
        addStateTransitionCondition(0x77);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackLeftC", 0x24);
        addState("GrabMeleeAttackLeftC", 0x25);
        addState("GrabMeleeAttackRightB", 0x26);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackRightCTrans", 8);
        stateHandle = getStateHandle("GrabMeleeAttackRightCTrans", 0xffffffff);
        setStateBlendParam(0x16, 0x1c, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabBreak", 0x45);
        addState("GrabMeleeAttackLeftC", 0x24);
        addState("GrabMeleeAttackLeftC", 0x25);
        addState("GrabMeleeAttackRightB", 0x26);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabThrowLeft", 0x3a);
        addState("GrabThrowRight", 0x3b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabChargeAttackLeftStart", 0xffffffff);
        setStateBlendParam(0x16, 0x1d, 1);
        setStateBlendParam(0x12, 1, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addStateTransitionCondition(0x81);
        setStateFlag(0x82);
        addState("GrabEndPaired", 0x13);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftFinish", 0x2a);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabIdle", 0x28);
        addState("GrabStrangle", 0x3e);
        addState("GrabBreak", 0x45);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabChargeAttackLeftHold", 8);
        stateHandle = getStateHandle("GrabChargeAttackLeftHold", 0xffffffff);
        setStateBlendParam(0x16, 0x1e, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x5b);
        addStateTransitionCondition(0x55);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        addStateConditional(0x57);
        setStateFlag(0x56);
        setStateFlag(0x2f);
        addStateTransitionCondition(0x81);
        setStateFlag(0x82);
        addState("GrabEndPaired", 0x13);
        addState("GrabBreak", 0x45);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackLeftFinish", 0x2a);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabIdle", 0x29);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        stateHandle = getStateHandle("GrabChargeAttackLeftFinish", 0xffffffff);
        setStateBlendParam(0x16, 0x1f, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0x1f, 1);
        setStateBlendParam(0x75, 9, 1);
        addStateTransitionCondition(0x76);
        addStateTransitionCondition(0x77);
        addStateConditionalArg(0x12, 0, 1);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addStateTransitionCondition(0x81);
        setStateFlag(0x82);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabChargeAttackRightStart", 0xffffffff);
        setStateBlendParam(0x16, 0x20, 1);
        setStateBlendParam(0x12, 1, 1);
        addStateTransitionCondition(0x31);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x2f);
        addStateTransitionCondition(0x81);
        setStateFlag(0x82);
        addState("GrabEndPaired", 0x13);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackRightFinish", 0x2e);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabIdle", 0x2c);
        addState("GrabStrangle", 0x3e);
        addState("GrabBreak", 0x45);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabChargeAttackRightHold", 8);
        stateHandle = getStateHandle("GrabChargeAttackRightHold", 0xffffffff);
        setStateBlendParam(0x16, 0x21, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x5b);
        addStateTransitionCondition(0x55);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        addStateConditional(0x57);
        setStateFlag(0x56);
        setStateFlag(0x2f);
        addStateTransitionCondition(0x81);
        setStateFlag(0x82);
        addState("GrabEndPaired", 0x13);
        addState("GrabBreak", 0x45);
        addState("GrabRelease", 0x1e);
        addState("GrabChargeAttackRightFinish", 0x2e);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabIdle", 0x2d);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        stateHandle = getStateHandle("GrabChargeAttackRightFinish", 0xffffffff);
        setStateBlendParam(0x16, 0x22, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x50);
        setStateBlendParam(0x69, 0x22, 1);
        setStateBlendParam(0x75, 9, 1);
        addStateTransitionCondition(0x76);
        addStateTransitionCondition(0x77);
        addStateConditionalArg(0x12, 0, 1);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x26);
        setStateFlag(0x6a);
        setStateFlag(0x2f);
        addStateTransitionCondition(0x81);
        setStateFlag(0x82);
        addState("GrabEndPaired", 0x13);
        addState("GrabKilledGrabbee", 0x30);
        addState("GrabRelease", 0x1e);
        addState("GrabPullup", 0x31);
        addState("GrabDropToKnees", 0x2f);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabStrangle", 0x3e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabDropToKnees", 0xffffffff);
        setStateBlendParam(0x16, 0x23, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        setStateFlag(0x51);
        addState("GrabEndPaired", 0x13);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabKilledGrabbee", 0xffffffff);
        addState("GrabEndPaired", 4);
        stateHandle = getStateHandle("GrabPullup", 0xffffffff);
        setStateBlendParam(0x16, 0x25, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x51);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        addStateConditional(0x6d);
        addState("GrabEndPaired", 0x13);
        addState("GrabRelease", 0x1e);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabIdle", 8);
        stateHandle = getStateHandle("GrabMoveForwardsRight", 0xffffffff);
        addStateTransitionCondition(0x7b);
        setStateBlendParam(0x16, 0x26, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x52);
        setStateBlendParam(0x6b, 0x14, 1);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        addStateConditional(0x4d);
        addStateConditional(0x54);
        setStateFlag(0x53);
        setStateFlag(0x2f);
        setStateFlag(0x7c);
        addState("GrabEndPaired", 0x13);
        addState("Execution", 0x4e);
        addState("GrabBreak", 0x45);
        addState("GrabThrowIntoStumble", 0x48);
        addState("GrabSlam", 0x43);
        addState("GrabThrowRight", 0x3b);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabHoldThrow", 0x42);
        addState("GrabRelease", 0x1e);
        addState("GrabMoveBackwardsRight", 0x34);
        addState("GrabMoveBackwardsLeft", 0x36);
        addState("GrabMoveForwardsLeft", 0x32);
        addState("GrabIdle", 0x39);
        addState("GrabIdle", 10);
        stateHandle = getStateHandle("GrabMoveBackwardsRight", 0xffffffff);
        addStateTransitionCondition(0x7b);
        setStateBlendParam(0x16, 0x27, 1);
        addStateTransitionCondition(0x31);
        addStateTransitionCondition(0x52);
        setStateBlendParam(0x6b, 0x14, 1);
        setStateAnimation(0x2e, DAT_00d5ef90, 1);
        addStateTransitionCondition(0x19);
        addStateConditional(0x1a);
        addStateConditional(0x4d);
        addStateConditional(0x54);
        setStateFlag(0x53);
        setStateFlag(0x2f);
        setStateFlag(0x7c);
        addState("GrabEndPaired", 0x13);
        addState("GrabBreak", 0x45);
        addState("Execution", 0x4e);
        addState("GrabSlam", 0x43);
        addState("GrabThrowRight", 0x3b);
        addState("PairedFinisher", 0x52);
        addState("Execution", 0x53);
        addState("Execution", 0x54);
        addState("GrabMeleeAttackLeftA", 0x24);
        addState("GrabMeleeAttackLeftA", 0x25);
        addState("GrabMeleeAttackRightA", 0x26);
        addState("GrabQuickAttackA", 0x1f);
        addState("GrabQuickAttackB", 0x20);
        addState("GrabQuickAttackC", 0x22);
        addState("GrabChargeAttackLeftStart", 0x27);
        addState("GrabChargeAttackRightStart", 0x2b);
        addState("GrabHoldThrow", 0x42);
        addState("GrabRelease", 0x1e);
        addState("GrabMoveForwardsRight", 0x38);
        addState("GrabMoveBackwardsLeft", 0x36);
        addState("GrabMoveForwardsLeft", 0x32);
        addState("GrabIdle", 0x35);
        addState("GrabIdle", 10);
        stateHandle = getStateHandle("GrabMoveBackwardsLeft", 0xffffffff);
        addStateTransitionCondition(0x7b);
        setStateBlendParam(0x16, 0x28, 1);
        add