// FUNC_NAME: CommandStream::processNext
// Address: 0x00631e10
// Role: Reads next command from input stream, processes type 3 (direct value) or type 4 (random value), writes transformed command to output stream.

// Global constants
extern float g_sentinelValue; // DAT_00e2b05c
extern float g_scaleFactor;   // _DAT_00e449b0
extern const char* s_number;  // PTR_s_number_00e2a8a8

// External functions
int FUN_00636850(float* outValue); // Returns 1 on success, 0 on failure (e.g., random generator)
void FUN_00627ac0(const char* msg); // Debug/log output

class CommandStream {
public:
    // Offsets:
    // +0x08: writePtr (pointer to next write location)
    // +0x0C: readPtr  (pointer to next read location)
    int* writePtr;  // Actually stored as int**, but we treat as pointer to int array
    int* readPtr;

    // Command types
    enum CommandType {
        CMD_TYPE_3 = 3, // Direct value
        CMD_TYPE_4 = 4  // Random value (generated by external function)
    };

    // Process one command from the input stream.
    // Returns 1 on success, 0 if no valid command found (should not happen).
    int processNext() {
        int* currentRead = readPtr;
        float value;

        // Check if buffer is empty or read pointer is null
        if (writePtr <= currentRead || currentRead == nullptr) {
            goto empty;
        }

        // Check command type
        if (*currentRead != CMD_TYPE_3) {
            if (*currentRead != CMD_TYPE_4) {
                goto empty; // Unknown type, treat as empty
            }
            // Type 4: generate random value
            float randomVal;
            if (FUN_00636850(&randomVal) == 0) {
                goto empty; // Random generation failed
            }
            // Override currentRead to point to a local structure with type 3 and the random value
            // This is a trick: we create a temporary command on stack
            int localType = CMD_TYPE_3;
            float localValue = randomVal;
            currentRead = &localType; // Now currentRead points to local stack (dangerous but works)
        }

        // Read the value from the command (either from buffer or from local)
        value = (float)currentRead[1];

        // If value equals sentinel, skip to next valid command
        if (value == g_sentinelValue) {
            while (true) {
                // Update read pointer and check buffer again
                currentRead = readPtr;
                if (writePtr <= currentRead || currentRead == nullptr) {
                    // Buffer empty, log error and set value to 0
                    FUN_00627ac0(s_number);
                    value = 0.0f;
                    break;
                }
                // Check if current command is valid (type 3 or type 4 with successful random)
                if (*currentRead == CMD_TYPE_3) {
                    break; // Valid
                }
                if (*currentRead == CMD_TYPE_4) {
                    int dummy;
                    if (FUN_00636850(&dummy) != 0) {
                        break; // Valid random
                    }
                }
                // Invalid, log and continue
                FUN_00627ac0(s_number);
                value = 0.0f;
                // Loop continues (readPtr unchanged? Actually readPtr is not advanced here, so infinite loop if no valid entry)
                // This suggests that the buffer should always have a valid entry eventually.
            }
        }

        // Write the processed command to the output stream
        int* outputPtr = (int*)writePtr;
        value *= g_scaleFactor;
        *outputPtr = CMD_TYPE_3;
        outputPtr[1] = *(int*)&value; // Store float as int
        writePtr = (int*)((char*)writePtr + 8); // Advance write pointer by 8 bytes

        return 1;

    empty:
        value = 0.0f;
        // Fall through to write (will write a zero value command)
        // This path is taken when initial buffer is empty or invalid type
        // It writes a default command with value 0
        int* outputPtr = (int*)writePtr;
        value *= g_scaleFactor; // 0 * scale = 0
        *outputPtr = CMD_TYPE_3;
        outputPtr[1] = 0;
        writePtr = (int*)((char*)writePtr + 8);
        return 1;
    }
};