// FUNC_NAME: PacketBuffer::writeStringField
// Address: 0x006363e0
// This function writes a 4-byte type identifier (0x4) followed by a 4-byte value
// generated by an internal helper. It parses a null-terminated string to compute
// the value (likely a hash or offset). Buffer management uses a double-indirection
// header pattern typical of EA EARS dynamic buffer system.

// Structure layout (offsets relative to 'this'):
//   +0x08 : uint8* m_writePos          (current write pointer)
//   +0x14 : BufferHeader** m_ppHeader  (pointer to pointer to buffer header)
//   +0x18 : uint8* m_bufferEnd         (end of allocated space)
// BufferHeader likely contains:
//   +0x00 : uint8* m_dataStart         (base address of data)
//   +0x04 : uint32 m_capacity          (total capacity)

// Helper function (0x00638920) returns a 32-bit value based on the string or internal state.
// Helper function (0x00635c70) expands the buffer.

#include <cstdint>

class PacketBuffer {
public:
    // Write a string field: type 4, followed by a computed value.
    bool writeStringField(const char* str) {
        // Get the current data start from the buffer header double-indirection.
        // m_ppHeader points to a pointer that points to the buffer header.
        BufferHeader* header = *m_ppHeader;
        uint8* dataStart = header->m_dataStart;

        // Set the write pointer to the beginning of data (possibly resetting?).
        m_writePos = dataStart;

        // Write the type identifier (4 = string).
        *(uint32*)dataStart = 4;

        // Skip the string to find its end (or to compute something).
        const char* p = str;
        while (*p != '\0') {
            p++;
        }
        // After the loop, p points to the null terminator.
        // The helper function likely uses p to compute the value.
        uint32 computedValue = getComputedValue();  // internal helper

        // Write the computed value at dataStart+4.
        *(uint32*)(dataStart + 4) = computedValue;

        // Check if the buffer has enough space for the 8-byte header + margin.
        // The condition checks if remaining space (m_bufferEnd - m_writePos) < 9.
        if (m_bufferEnd - m_writePos < 9) {
            expandBuffer();  // grow the buffer
        }

        // Advance the write pointer by 8 bytes (the two uint32 fields).
        m_writePos += 8;

        return true;
    }

private:
    // Internal helpers (addresses known)
    uint32 getComputedValue();
    void expandBuffer();

    // Structure fields
    uint8* m_writePos;       // +0x08
    uint8* m_bufferEnd;      // +0x18
    BufferHeader** m_ppHeader; // +0x14
};

// Forward declaration of internal struct
struct BufferHeader {
    uint8* m_dataStart;  // +0x00
    uint32 m_capacity;   // +0x04
};